//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ba_Jet_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PrepsEntities : DbContext
    {
        public DB_PrepsEntities()
            : base("name=DB_PrepsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<expensedet> expensedets { get; set; }
        public virtual DbSet<shareholder> shareholders { get; set; }
        public virtual DbSet<cred> creds { get; set; }
    }
}
