//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ba_Jet_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class cred
    {
        public Nullable<int> usrid { get; set; }
        public string usrname { get; set; }
        public string passwd { get; set; }
    
        public virtual shareholder shareholder { get; set; }
    }
}
