//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ba_Jet_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class expensedet
    {
        public int exp_id { get; set; }
        public string exp_Catg { get; set; }
        public string exp_for { get; set; }
        public decimal exp_amount { get; set; }
        public Nullable<int> exp_spentby { get; set; }
    
        public virtual shareholder shareholder { get; set; }
        public virtual shareholder shareholder1 { get; set; }
    }
}
